title: "My Data Engineering Portfolio"
description: "Showcasing my work, projects, and expertise in data engineering."
show_downloads: false
theme: jekyll-theme-minimal

header_pages:
  - index.md
  - about.md
  - projects.md

social_links:
  - name: "GitHub"
    url: "https://github.com/mukesh61"
  - name: "LinkedIn"
    url: "https://linkedin.com/in/mukeshmahato"

author:
  name: "Mukesh Mahato"
  bio: "Data Engineer | Python | AWS Cloud | Kafka"
